### ISSUE TITLE
Texts not Justified

### ISSUE THREAD

**Issue by Dishebh** [fossasia/summit.fossasia.org#20]
**Actual Behaviour**

The texts in the website are not justified. This makes it not very pretty. 

**Expected Behaviour**

The texts present in the website should be justified.

**Steps to reproduce it**

* go to the [website](https://www.2019.fossasia.org)
* You'll see the texts present are not looking very neat and need to be justified.

**Screenshots of the issue**

![Screenshot from 2019-12-16 02-02-42](https://user-images.githubusercontent.com/43489708/70868602-4624b900-1fa8-11ea-979b-d76e6ab01389.png)
![Screenshot from 2019-12-16 02-02-55](https://user-images.githubusercontent.com/43489708/70868603-491fa980-1fa8-11ea-804e-248eecddcd91.png)

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
No need
