### ISSUE TITLE
Add confirmed sponsors 

### ISSUE THREAD

**Issue by edenyay** [fossasia/summit.fossasia.org#30]
**Actual Behaviour**
no sponsors added yet 

**Expected Behaviour**
confirmed sponsors to be added together with their sponsorship tiers & link to their websites 

**Steps to reproduce it**
1. [Google](https://opensource.google) as Gold Sponsor
2. [Facebook ](https://www.facebook.com)as Gold Sponsor
3. [Github](https://github.com) as Gold Sponsor 
4. [Arm ](https://www.arm.com)as Silver Sponsor
5. [Gandi](http://gandi.net) as Bronze Sponsor
6. [Flowchain](https://flowchain.co) as Bronzer Sponsor

**Comment by pkspyder007** [comment]
@edenyay Can i work on this issue?

**Comment by Dishebh** [comment]
@pkspyder007 are you working on this issue? if not, can I take this up?

**Comment by Dishebh** [comment]
@edenyay Pls have a look at the above PR, see if it solves the issue?
