### ISSUE TITLE
Remove UNESCO Bangkok as co-organizer 

### ISSUE THREAD

**Issue by edenyay** [fossasia/summit.fossasia.org#31]
**Actual Behaviour**
UNESCO Bangkok listed as co-organizer, which is incorrect 

![Screen Shot 2019-12-23 at 19 47 09](https://user-images.githubusercontent.com/32028823/71358893-28b1a980-25bd-11ea-847b-76095ab9d7d6.png)

**Expected Behaviour**
to remove UNESCO Bangkok as co-organizer

**Comment by ayushmankumar7** [comment]
What should be the substitute for Bangkok ? Can I work on this?
