### ISSUE TITLE
Add Bella Phan into Team Section 

### ISSUE THREAD

**Issue by hpdang** [fossasia/summit.fossasia.org#32]
**Actual Behaviour**
Missing photo of Bella Phan
![bella](https://user-images.githubusercontent.com/1658742/71365840-7966d980-25a0-11ea-928f-f5544b53417c.jpg)

**Expected Behaviour**
- Photo of Bella Phan is added into the team section at the potion of Lorenz Gerber 
- Remove Lorenz Gerber

**Comment by ektaarora3501** [comment]
Hello , I am to new to code base.. Can I take this issue ?

**Comment by ayushmankumar7** [comment]
Can you assgin this to me?

**Comment by pkspyder007** [comment]
@ektaarora3501 Hello Ekta, if you are currently working on this issue please let me so i could choose on some other issue.

**Comment by Dishebh** [comment]
Is anyone working on the issue? If not, can I take this up?

**Comment by ektaarora3501** [comment]
@pkspyder007  I am not assigned this issue . I guess PR is already opened by @Dishebh

**Comment by Dishebh** [comment]
@hpdang pls have a look at the above PR, see if it solves the issue?
