### ISSUE TITLE
Update logo for Flowchain

### ISSUE THREAD

**Issue by edenyay** [fossasia/summit.fossasia.org#38]
hello,  I uploaded the uploaded the new version of Flowchain's logo quite some time ago, but the old logo still appears in the website. Would be great if you can help me replace it.  

The new logo can be found here:  @https://drive.google.com/open?id=1pTWn8GjeHyxtIlH-hehgrxgIR06Pt7ha (the orange horizontal one with Flowchain text)  Thank you!

**Comment by hpdang** [comment]
done
