### ISSUE TITLE
Add Elastic as Bronze Sponsor 

### ISSUE THREAD

**Issue by edenyay** [fossasia/summit.fossasia.org#41]
**Actual Behaviour**
Missing Elastic logo 

**Expected Behaviour**
Adding Elastic logo under Bronze Sponsor section

Logo:
![elastic-logo-H-full color](https://user-images.githubusercontent.com/32028823/73602999-a353e880-45af-11ea-9125-e9d60604e21f.png)

**Comment by NishithP2004** [comment]
Im claiming this issue

**Comment by jatin2003** [comment]
@NishithP2004 I've created PR:- https://github.com/fossasia/summit.fossasia.org/pull/42

**Comment by edenyay** [comment]
The logo of Elastic was not displayed in .png format (the background is not transparent) as in the attached photo. I reuploaded the image again, could you fix this? Thank you!

![elastic-logo-H-full color](https://user-images.githubusercontent.com/32028823/74339805-c0728d80-4ddf-11ea-94fa-dd5eb54cec25.png)

**Comment by NishithP2004** [comment]
> The logo of Elastic was not displayed in .png format (the background is not transparent) as in the attached photo. I reuploaded the image again, could you fix this @jatin2003 @NishithP2004 ? Thank you!
> 
> ![elastic-logo-H-full color](https://user-images.githubusercontent.com/32028823/74339805-c0728d80-4ddf-11ea-94fa-dd5eb54cec25.png)

Sure
