### ISSUE TITLE
Add Instaclustr as Silver Sponsor 

### ISSUE THREAD

**Issue by edenyay** [fossasia/summit.fossasia.org#45]
Actual Behaviour
Missing Instaclustr logo

Expected Behaviour
Adding Instaclustr logo under Silver Sponsor section with the URL: https://www.instaclustr.com

Logo:
![800px-Instaclustr_Logo_-_Wiki](https://user-images.githubusercontent.com/32028823/73667320-adbcd200-46d6-11ea-9d73-c1d57344fc2c.png)

**Comment by NishithP2004** [comment]
I'm on it

**Comment by jatin2003** [comment]
@NishithP2004 I'm working on this!
