### ISSUE TITLE
Add 'proudly supported by' section 

### ISSUE THREAD

**Issue by edenyay** [fossasia/summit.fossasia.org#46]
**Actual Behaviour**
The current summit site is missing the Proudly supported by section (below the logos of sponsors), view sample from last year here: http://2019.fossasia.org

**Expected Behaviour**
Adding Proudly supported by section using the logos and url of the supporters as below:
The below logos should be put from left to right and then down in an order. As sample screen captured from last year: 

![Screen Shot 2020-02-03 at 22 58 40](https://user-images.githubusercontent.com/32028823/73668690-d2b24480-46d8-11ea-8c9d-029788cf3f5b.png)

1. Science Center https://www.science.edu.sg
![sciencecentre-white](https://user-images.githubusercontent.com/32028823/73670577-0d69ac00-46dc-11ea-9aa0-c3790c9bcfb7.png)

2. LPI: https://www.lpi.org
<img width="250" alt="LPI" src="https://user-images.githubusercontent.com/32028823/73670652-32f6b580-46dc-11ea-93d1-40f3b195409b.png">

3. FreeBSD Foundation: https://www.freebsdfoundation.org
![Freebsd](https://user-images.githubusercontent.com/32028823/73670693-46a21c00-46dc-11ea-83f1-bf0874f86e9c.png)

4. CentOS: https://www.centos.org
![CentOS](https://user-images.githubusercontent.com/32028823/73671459-8fa6a000-46dd-11ea-99d5-8ae2f62e6128.png)

5. IndependIT: https://independit.de
![independIT](https://user-images.githubusercontent.com/32028823/73671536-b9f85d80-46dd-11ea-9868-28e81606f70f.png)

6. Uilicious https://uilicious.com
![uilicious](https://user-images.githubusercontent.com/32028823/73671603-d85e5900-46dd-11ea-82c4-e7ae02d594fd.png)

7. WeWe Tech JSC https://wewe.vn
![WEWE-LOGO](https://user-images.githubusercontent.com/32028823/73671783-4014a400-46de-11ea-9877-df5f987b40f3.png)

8. wolfssl: https://www.wolfssl.com
![wolfssl_logo-300x232](https://user-images.githubusercontent.com/32028823/73671847-66d2da80-46de-11ea-8452-5866a4788efc.png)

**Comment by jatin2003** [comment]
I'm claiming this issue.
