### ISSUE TITLE
Replace block-text section UNESCO Hackathon by Linux Professional Institute Exam Lab

### ISSUE THREAD

**Issue by edenyay** [fossasia/summit.fossasia.org#47]
**Actual Behaviour**
The current block-text section UNESCO Hackathon (as in screenshot) is out of date. We need to replace with the new information & link.

![Screen Shot 2020-02-04 at 10 42 24](https://user-images.githubusercontent.com/32028823/73711934-1473d700-473b-11ea-8912-be136d184fb4.png)

**Expected Behaviour**
Replace block-text section UNESCO Hackathon by Linux Professional Institute Exam Lab

(Title) 
Linux Professional Institute Exam Lab
Saturday March 21, 10:00 - 13:00

(Body) 
Linux Professional Institute is thrilled to be offering exams at a discounted rate
exclusively to FOSSASIA attendees. While at FOSSASIA, write the Linux Essentials for $75
USD, DevOps Tools Engineer for $99 USD, BSD Specialist for $99 USD, LPIC for $99 USD.
Please register in advance. You can provide advance payment by Paypal or credit card (a
choice within the Paypal link). You have the opportunity to take up to 2 exams within this
exam lab. The exam will be presented and provided in English.

Keep the **sign up here** button, but redirect to: https://pretix.eu/lpi.org/9rwwp

Replace the photo on the right with the photo below:
![IMG_4009 CR2](https://user-images.githubusercontent.com/32028823/73712220-f6f33d00-473b-11ea-9b55-a87783f28669.jpg)

**Comment by NishithP2004** [comment]
I'm on it

**Comment by edenyay** [comment]
@NishithP2004 image cannot be displayed, the sign up link was not updated. Could you give it a quick look again, please?

**Comment by NishithP2004** [comment]
> @NishithP2004 image cannot be displayed, the sign up link was not updated. Could you give it a quick look again, please?

Sorry for the errors in the previous PR, I have done the changes properly in the above PR.
