### ISSUE TITLE
Image problem due to Page responsiveness

### ISSUE THREAD

**Issue by Valdermaut** [fossasia/summit.fossasia.org#5]
Actual Behaviour

When the 2020.fossasia.org site loads, there are a few bugs in the image-with-text testimonials preserve-3ds section of the page. The issue is seen while viewing the page in iPad and iPad Pro resolutions : 1024x1366 the image and the text for one of div specifically the 
FOSSASIA Exhibition Tech Companies & Projects from Thu March 19 - Sun March 22 merges with the image.
![fossasia](https://user-images.githubusercontent.com/43613722/64731557-18d6f380-d4ff-11e9-82ab-32c101c24a40.png)

The screenshots have been attached below.

Expected Behaviour

The text should not merge with the image.

Steps to reproduce it

Open the FossAsia 2020 Summit Site
Scroll to the Topics and Tracks Section
Open Developer Tools (Ctrl+Shift+I on Chrome)
Choose the Window size as iPad or iPad Pro, the bug can be seen
Screenshots of the issue

**Comment by lokendraporwal** [comment]
Yeah there is a major issue in responsiveness of the website. I also tried in different sizes and almost in every device issue can be seen expect on PC in full screen mode.

**Comment by Valdermaut** [comment]
yes there are issues at certain divs and because of which the
responsiveness is getting affected, is there some approach you suggest?

**Comment by SohelRaja** [comment]
@Valdermaut can I work on this?

**Comment by Valdermaut** [comment]
yeah sure go on with it

**Comment by SohelRaja** [comment]
@Valdermaut I have fixed it.
