### ISSUE TITLE
Update new logo for Facebook 

### ISSUE THREAD

**Issue by edenyay** [fossasia/summit.fossasia.org#56]
**Actual Behaviour**

The current Facebook's logo under Gold Sponsor is outdated. 

**Expected Behaviour**

Replace current logo with new logo as in attachment, make sure its background is transparent. Keep the link: https://opensource.facebook.com

![Facebook-Wordmark-Gray](https://user-images.githubusercontent.com/32028823/74603405-cd47f780-50e5-11ea-9bd3-281cb7e091eb.png)

**Comment by snitin315** [comment]
On it
